fix(pattern): Fix mongodb patterns, assert all patterns in debug profile (#4125)
Assert patterns for correctness in the debug profile. This caught the
mongodb patterns to be broken because of unbalanced parenthesis.

Example failure of the MongoDB patterns:

```
---- metrics_extraction::event::tests::test_metrics_summaries_on_transaction_and_spans stdout ----
thread 'metrics_extraction::event::tests::test_metrics_summaries_on_transaction_and_spans' panicked at /home/runner/work/relay/relay/relay-pattern/src/typed.rs:185:18:
all patterns should be valid patterns: Error { pattern: "*[{*", kind: UnbalancedCharacterClass }
```

Fixing the mongodb patterns surfaced a bug in matching of the
`db.system`, which is now also fixed.