fix(ci): Increase sleep and timeout in flakey tests (#5277)
The following tests have been incredibly flakey recently, this PR is an
attempt at fixing that:
```
FAILED tests/integration/test_autoscaling.py::test_sqlite_spooling_metrics - requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=40733): Max retries exceeded with url: /api/42/store/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff50611af10>: Failed to establish a new connection: [Errno 111] Connection refused'))
FAILED tests/integration/test_nel.py::test_nel_converted_to_logs - _queue.Empty
```