fix(beta): Remove the warning of the beta linter (#3931)
Following warning was reporter on beta:
```
error: the borrowed expression implements the required traits
   --> relay-event-normalization/src/trimming.rs:700:48
    |
700 |             let other = match contexts.get_key(&format!("despacito{i}")).unwrap() {
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `format!("despacito{i}")`
```

which does not require taking a reference anymore.