fix(server): Drop runtimes in sync context on error (#2420)
Tokio runtimes should not be dropped from within an asynchronous
context. In the success case, this was previously guaranteed by
explicitly dropping the service state. When starting the service state
failed (for example because of a faulty kafka config), relay would still
panic. This PR prevents the panic by keeping the runtimes alive outside
of the service state.

Before:

```
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed.
This happens when a runtime is dropped from within an asynchronous context.'
```

After:

```
error=failed to create kafka producer: invalid kafka config
error.sources=[Client config error: No such configuration property ...
```